require "strscan"
require "pathname"
require "strong_json"
require "yaml"
require "json"
require "active_support/core_ext/hash/indifferent_access"
require "active_support/core_ext/integer/inflections"
require "rainbow"

require "goodcheck/version"

require "goodcheck/glob"
require "goodcheck/buffer"
require "goodcheck/location"
require "goodcheck/reporters/text"
require "goodcheck/reporters/json"
require "goodcheck/array_helper"
require "goodcheck/analyzer"
require "goodcheck/issue"
require "goodcheck/rule"
require "goodcheck/pattern"
require "goodcheck/config"
require "goodcheck/config_loader"
require "goodcheck/commands/config_loading"
require "goodcheck/commands/check"
require "goodcheck/commands/init"
require "goodcheck/commands/test"
